create table if not exists public.portfolio_content (
  id text primary key,
  projects jsonb not null default '[]'::jsonb,
  education jsonb not null default '[]'::jsonb,
  assets jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.portfolio_content enable row level security;

insert into public.portfolio_content (id)
values ('main')
on conflict (id) do nothing;

create table if not exists public.contact_messages (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  status text not null default 'received',
  created_at timestamptz not null default now()
);

alter table public.contact_messages enable row level security;