import { motion } from 'framer-motion'
import { ArrowRight, Check, GraduationCap } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useEducation } from '../../hooks/useEducation.js'

export default function HomeAcademicFlow() {
  const { items, loading } = useEducation()

  return <section className="border-b border-[var(--border)] bg-[color:var(--bg)] py-14 md:py-20"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.1em] text-[var(--accent)]">Academic journey</p><h2 className="mt-3 text-3xl font-extrabold tracking-[-.055em] text-[var(--text)] sm:text-4xl">Learning in motion.</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[var(--muted)]">A quick view of the milestones shaping my engineering perspective.</p></div><Link to="/academics" className="inline-flex items-center gap-2 text-xs font-bold text-[var(--accent)] transition hover:text-[var(--accent-2)]">View full academic record <ArrowRight size={14} /></Link></div><div className="relative overflow-x-auto pb-3"><div className="absolute left-8 right-8 top-[29px] hidden h-px bg-gradient-to-r from-[var(--accent)]/70 via-[var(--accent-2)]/70 to-[var(--muted)]/20 md:block" /><div className="relative grid min-w-[620px] grid-cols-2 gap-5 md:grid-cols-4">{loading ? Array.from({ length: 2 }, (_, index) => <AcademicNodeSkeleton key={index} />) : items.map((item, index) => <AcademicNode item={item} index={index} key={item.id || `${item.institution}-${item.period}`} />)}</div></div></section>
}

function AcademicNodeSkeleton() { return <article className="animate-pulse" aria-hidden="true"><div className="size-[58px] rounded-full bg-[var(--panel)]" /><div className="mt-5 space-y-3 rounded-xl border border-[var(--border)] bg-[color:var(--panel)] p-4"><div className="h-2 w-24 rounded bg-[var(--panel)]" /><div className="h-4 w-3/4 rounded bg-[var(--panel)]" /><div className="h-3 w-32 rounded bg-[var(--panel)]" /><div className="h-3 w-full rounded bg-[var(--panel)]" /><div className="h-3 w-2/3 rounded bg-[var(--panel)]" /></div></article> }

function AcademicNode({ item, index }) {
  const isCurrent = Boolean(item.current)
  return <motion.article initial={{ opacity: 0, x: index % 2 ? 22 : -22 }} whileInView={{ opacity: 1, x: 0 }} viewport={{ once: true, amount: .3 }} transition={{ delay: index * .1, duration: .5 }} className="group relative"><div className={`relative z-10 grid size-[58px] place-items-center rounded-full border-4 border-[var(--bg)] shadow-lg transition duration-300 group-hover:scale-110 ${isCurrent ? 'bg-emerald-500 text-white shadow-emerald-500/30' : 'bg-[var(--panel)] text-[var(--accent)] shadow-[var(--shadow)]'}`}>{isCurrent ? <span className="relative"><GraduationCap size={21} /><i className="absolute -right-2 -top-2 size-2 rounded-full bg-white shadow-[0_0_8px_white]" /></span> : <Check size={19} />}</div><div className="mt-5 rounded-xl border border-[var(--border)] bg-[color:var(--panel)] p-4 transition duration-300 group-hover:-translate-y-1 group-hover:border-[var(--accent)]/40"><div className="flex items-center justify-between gap-2"><span className="font-mono text-[9px] text-[var(--accent)]">{item.period}</span><span className={`rounded-full px-2 py-1 text-[9px] ${isCurrent ? 'bg-emerald-500/10 text-emerald-500' : 'bg-[color:var(--panel-strong)] text-[var(--muted)]'}`}>{isCurrent ? 'Current' : 'Completed'}</span></div><h3 className="mt-3 text-sm font-bold leading-5 text-[var(--text)]">{item.title}</h3><p className="mt-2 text-[11px] font-semibold text-[var(--muted)]">{item.institution}</p><p className="mt-3 line-clamp-2 text-[11px] leading-5 text-[var(--muted)]">{item.detail}</p></div></motion.article>
}
