import { ArrowUpRight } from 'lucide-react'
import { Link } from 'react-router-dom'
import { profile } from '../data/portfolio.js'
import HeroSection from '../components/sections/HeroSection.jsx'
import HomeAcademicFlow from '../components/sections/HomeAcademicFlow.jsx'

export default function HomePage() {
  return <><HeroSection /><section className="grid gap-8 border-y border-white/10 py-12 md:grid-cols-[1.2fr_.8fr] md:py-16"><div><p className="font-mono text-[10px] uppercase tracking-[.09em] text-indigo-300">A little about me</p><h2 className="mt-4 text-3xl font-extrabold tracking-[-.05em] text-slate-100 sm:text-4xl">Software with a human point of view.</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-slate-400">{profile.about}</p><Link to="/about" className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-indigo-300 hover:text-indigo-200">Read my story <ArrowUpRight size={14} /></Link></div><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5"><div className="flex items-center justify-between"><span className="text-xs font-bold text-slate-200">Current focus</span><span className="font-mono text-[10px] text-emerald-400">2025</span></div><FocusBar label="Product engineering" value="88%" width="88%" /><FocusBar label="Mobile & web systems" value="76%" width="76%" /><FocusBar label="Learning in public" value="92%" width="92%" /></div></section><HomeAcademicFlow /><section className="border-b border-white/10 py-7"><div className="flex flex-wrap items-center justify-between gap-5 font-mono text-[10px] text-slate-500"><span>Explore the portfolio</span><div className="flex flex-wrap gap-4 font-sans text-xs font-bold text-slate-400 sm:gap-6"><Link to="/projects" className="inline-flex items-center gap-1 hover:text-indigo-300">Selected work <ArrowUpRight size={13} /></Link><Link to="/contact" className="inline-flex items-center gap-1 hover:text-indigo-300">Contact <ArrowUpRight size={13} /></Link></div></div></section></>
}

function FocusBar({ label, value, width }) { return <div className="mt-5"><div className="mb-2 flex justify-between text-[10px] text-slate-400"><span>{label}</span><span>{value}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-800"><i className="block h-full rounded-full bg-gradient-to-r from-indigo-500 to-emerald-400" style={{ width }} /></div></div> }
