import { ArrowLeft, CalendarDays, Check, Code2, ExternalLink, Layers3, UserRound } from 'lucide-react'
import { Link, useParams } from 'react-router-dom'
import { useProjects } from '../hooks/useProjects.js'

export default function ProjectDetailPage() {
  const { projectId } = useParams()
  const { items, loading } = useProjects()
  const project = items.find((item) => item.id === projectId)
  if (loading) return <ProjectDetailSkeleton />
  if (!project) return <section className="py-20 pb-36"><Link to="/projects" className="text-sm text-indigo-300">Back to projects</Link><h1 className="mt-8 text-4xl font-extrabold text-slate-100">Project not found</h1></section>

  return <article className="py-12 pb-24 md:py-20 md:pb-36"><Link to="/projects" className="inline-flex items-center gap-2 text-xs text-slate-400 transition hover:text-indigo-300"><ArrowLeft size={15} /> Back to projects</Link><div className="mt-10 max-w-4xl"><span className="font-mono text-[10px] uppercase tracking-[.12em] text-indigo-300">{project.type}</span><h1 className="mt-4 text-5xl font-extrabold leading-tight tracking-[-.07em] text-slate-100 sm:text-7xl">{project.title}</h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-400">{project.description}</p><div className="mt-7 flex flex-wrap gap-2">{project.tags.map((tag) => <span key={tag} className="rounded-full border border-indigo-400/20 bg-indigo-500/10 px-3 py-1.5 text-xs text-indigo-200">{tag}</span>)}</div></div><div className="mt-12 grid gap-4 sm:grid-cols-3"><Meta icon={UserRound} label="Role" value={project.role || 'Product developer'} /><Meta icon={CalendarDays} label="Duration" value={project.duration || 'Ongoing'} /><Meta icon={Layers3} label="Features" value={`${project.features.length} core features`} /></div><div className="mt-12 grid gap-10 lg:grid-cols-[1.2fr_.8fr]"><div><h2 className="text-2xl font-bold text-slate-100">Inside the project</h2><p className="mt-4 text-sm leading-8 text-slate-400">{project.overview || project.description}</p><h2 className="mt-10 text-2xl font-bold text-slate-100">Core features</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{project.features.map((feature) => <li key={feature} className="flex items-start gap-2 rounded-lg border border-slate-800 bg-slate-900/50 p-4 text-xs leading-5 text-slate-300"><Check size={15} className="mt-0.5 shrink-0 text-emerald-400" />{feature}</li>)}</ul></div><div className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5"><h2 className="text-lg font-bold text-slate-100">Explore further</h2><div className="mt-5 grid gap-3">{project.liveUrl && <a href={project.liveUrl} target="_blank" rel="noreferrer" className="inline-flex items-center justify-between rounded-lg bg-indigo-500 px-4 py-3 text-xs font-bold text-white hover:bg-indigo-400">Live project <ExternalLink size={15} /></a>}<a href={project.sourceUrl || 'https://github.com'} target="_blank" rel="noreferrer" className="inline-flex items-center justify-between rounded-lg border border-slate-700 px-4 py-3 text-xs text-slate-300 hover:border-indigo-400">Source code <Code2 size={15} /></a></div></div></div><Gallery images={project.images} title={project.title} /></article>
}

function ProjectDetailSkeleton() { return <section className="animate-pulse py-12 pb-24 md:py-20 md:pb-36" aria-hidden="true"><div className="h-3 w-28 rounded bg-slate-800" /><div className="mt-10 max-w-4xl space-y-5"><div className="h-3 w-32 rounded bg-slate-800" /><div className="h-14 w-3/4 rounded bg-slate-800" /><div className="h-4 w-full max-w-2xl rounded bg-slate-800" /><div className="h-4 w-2/3 rounded bg-slate-800" /></div><div className="mt-12 grid gap-4 sm:grid-cols-3">{Array.from({ length: 3 }, (_, index) => <div className="h-24 rounded-xl border border-slate-800 bg-slate-900/50" key={index} />)}</div><div className="mt-12 grid gap-10 lg:grid-cols-[1.2fr_.8fr]"><div className="space-y-4"><div className="h-7 w-48 rounded bg-slate-800" /><div className="h-4 w-full rounded bg-slate-800" /><div className="h-4 w-5/6 rounded bg-slate-800" /></div><div className="h-48 rounded-2xl border border-slate-800 bg-slate-900/50" /></div></section> }
function Meta({ icon: Icon, label, value }) { return <div className="rounded-xl border border-slate-800 bg-slate-900/50 p-4"><Icon size={17} className="text-cyan-300" /><span className="mt-3 block text-[10px] text-slate-500">{label}</span><strong className="mt-1 block text-sm text-slate-200">{value}</strong></div> }
function Gallery({ images, title }) { if (!images?.length) return <div className="mt-14 rounded-2xl border border-dashed border-slate-700 bg-slate-900/30 p-10 text-center text-sm text-slate-500">Project screenshots will appear here when the owner adds them.</div>; return <section className="mt-14"><h2 className="text-2xl font-bold text-slate-100">Project screenshots</h2><div className="mt-5 grid gap-4 sm:grid-cols-2">{images.map((image, index) => <img key={`${image.slice(-20)}-${index}`} src={image} alt={`${title} screenshot ${index + 1}`} className="aspect-video w-full rounded-xl border border-slate-800 object-cover shadow-xl shadow-black/20" />)}</div></section> }
